
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._customerRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._countryRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._customerStatusRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._documentTypeRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._eventStoreRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService._onboardingStepRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.CustomerService.Bus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.OnboardingService._customerRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.OnboardingService._eventStoreRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.OnboardingService._mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.OnboardingService.Bus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneConfirmationService._customerRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneConfirmationService._eventStoreRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneConfirmationService._mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneConfirmationService._phoneConfirmationCodeRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneConfirmationService.Bus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneService._customerRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneService._eventStoreRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneService._mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneService._phoneRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "Necessary for Dependency Injection", Scope = "member", Target = "~F:Bank.Application.Services.PhoneService.Bus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Bank.Application.Services.BankTypesService._mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Bank.Application.Services.BankTypesService.Bus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Bank.Application.Services.ProspectService._eventStoreRepository")]

